@host = http://localhost:8080
@token = eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwiZW1haWwiOiJzdXBlckB0ZXN0LmNvbSIsInJvbGUiOiJTVVBFUiIsImlhdCI6MTc3NzUzMjI4NiwiZXhwIjoxNzc3NjE4Njg2fQ.rBuYQKsvIEUHjwkYexRybRe-mxqf9IXgxfy27tZn6Y0

### 1. 관리자 로그인
POST {{host}}/admins/login
Content-Type: application/json

{
  "email": "super@test.com",
  "password": "sparta1234"
}

### 2. 관리자 로그아웃
POST {{host}}/admins/logout
Authorization: Bearer {{token}}