@host = http://localhost:8080
@token = eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwiZW1haWwiOiJzdXBlckB0ZXN0LmNvbSIsInJvbGUiOiJTVVBFUiIsImlhdCI6MTc3NzUxMjg4MywiZXhwIjoxNzc3NTk5MjgzfQ.mYkkehW2zNxSViOmqw5kxjXJ6nKwn3R6I93vgXBXBc4

### 리뷰 목록 조회
GET {{host}}/reviews
Authorization: Bearer {{token}}


### 리뷰 목록 조회 - 검색 / 평점 필터 / 페이지네이션
GET {{host}}/reviews?keyword=마우스&rating=5&page=0&size=10&sort=createdAt,desc
Authorization: Bearer {{token}}


### 리뷰 상세 조회
GET {{host}}/reviews/1
Authorization: Bearer {{token}}


### 리뷰 삭제
DELETE {{host}}/reviews/1
Authorization: Bearer {{token}}