@host = http://localhost:8080
@token = eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwiZW1haWwiOiJzdXBlckB0ZXN0LmNvbSIsInJvbGUiOiJTVVBFUiIsImlhdCI6MTc3NzUzMjExNCwiZXhwIjoxNzc3NjE4NTE0fQ.U3Ec9tICmGv6hlTaxWJY7L6ud6D_q5P8g738s-R6aqI

### 대시보드 전체 데이터 조회
GET {{host}}/dashboard
Authorization: Bearer {{token}}