@host = http://localhost:8080
@token = eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwiZW1haWwiOiJzdXBlckB0ZXN0LmNvbSIsInJvbGUiOiJTVVBFUiIsImlhdCI6MTc3NzUxMjg4MywiZXhwIjoxNzc3NTk5MjgzfQ.mYkkehW2zNxSViOmqw5kxjXJ6nKwn3R6I93vgXBXBc4

### 대시보드 전체 데이터 조회
GET {{host}}/dashboard
Authorization: Bearer {{token}}